/* -*- Mode: C; indent-tabs-mode: t; c-basic-offset: 2; tab-width: 2 -*- */
/* gdome.c
 *
 * Copyright (C) 1999 Raph Levien <raph@acm.org>
 * Copyright (C) 2000 Mathieu Lacage <mathieu@gnu.org>
 * CopyRight (C) 2001 Paolo Casarini <paolo@casarini.org>
 *
 * This file is generated automatically.  To make changes, edit
 * test/apigen/core.xml
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

#ifndef GPDOMDefaultImpl_h
#define GPDOMDefaultImpl_h
#include <GPRuntime.h>
#include <GPPlugin.h>

/*Based on DOM events*/

#ifdef __cplusplus
extern "C" {
#endif

#define GP_DOM_DEFAULT_MIMETYPE "dom/default"

/**
 * This enum is provided for ease of use
 * by implementors using a interpeter like implementation
 * used internally in Generic Player
 */
typedef enum {
    GPDOM_LIBRARY_OPEN,  /*do not change magic impl used lib*/
    GPDOM_PLUGIN_CREATE,
    GPDOM_PLUGIN_DESTROY,
    GPDOM_PLUGIN_PROCESS_EVENT,
    GPDOM_PLUGIN_INHERIT,
    GPDOM_PLUGIN_GET_DOM_IMPLEMENTATION_REGISTERY,
    GPDOM_OBJECT_GET_METHOD,
    GPDOM_OBJECT_GET_MEMBER,
    GPDOM_DOM_IMPLEMENTATION_REGISTERY_GET_DOM_IMPLEMENTATION,
    GPDOM_DOM_IMPLEMENTATION_REGISTERY_GET_DOM_IMPLEMENTATION_LIST,
    GPDOM_DOM_IMPLEMENTATION_REGISTERY_REGISTER_DOM_IMPLEMENTATION_SOURCE,
    GPDOM_DOM_IMPLEMENTATION_REGISTERY_REGISTER_DOM_EVENT_SOURCE,
    GPDOM_DOM_IMPLEMENTATION_REGISTERY_REMOVE_DOM_EVENT_SOURCE,
    GPDOM_DOM_IMPLEMENTATION_SOURCE_GET_DOM_IMPLEMENTATION,
    GPDOM_DOM_IMPLEMENTATION_SOURCE_GET_DOM_IMPLEMENTATION_LIST,
    GPDOM_DOM_IMPLEMENTATION_LIST_GET_LENGTH,
    GPDOM_DOM_IMPLEMENTATION_LIST_GET_LENGTH_ITEM,
    GPDOM_DOM_IMPLEMENTATION_HAS_FEATURE,
    GPDOM_DOM_IMPLEMENTATION_CREATE_DOCUMENT_TYPE,
    GPDOM_DOM_IMPLEMENTATION_CREATE_DOCUMENT,
    GPDOM_DOM_IMPLEMENTATION_GET_FEATURE,
    GPDOM_NODE_GET_METHOD,
    GPDOM_NODE_GET_MEMBER,
    GPDOM_NODE_GET_NODE_NAME,
    GPDOM_NODE_GET_NODE_VALUE,
    GPDOM_NODE_SET_NODE_VALUE,
    GPDOM_NODE_GET_NODE_TYPE,
    GPDOM_NODE_GET_PARENT_NODE,
    GPDOM_NODE_GET_CHILD_NODES,
    GPDOM_NODE_GET_FIRST_CHILD,
    GPDOM_NODE_GET_LAST_CHILD,
    GPDOM_NODE_GET_PREVIOUS_SIBLING,
    GPDOM_NODE_GET_NEXT_SIBLING,
    GPDOM_NODE_GET_ATTRIBUTES,
    GPDOM_NODE_GET_OWNER_DOCUMENT,
    GPDOM_NODE_INSERT_BEFORE,
    GPDOM_NODE_REPLACE_CHILD,
    GPDOM_NODE_REMOVE_CHILD,
    GPDOM_NODE_APPEND_CHILD,
    GPDOM_NODE_HAS_CHILD_NODES,
    GPDOM_NODE_CLONE_NODE,
    GPDOM_NODE_NORMALIZE,
    GPDOM_NODE_IS_SUPPORTED,
    GPDOM_NODE_GET_NAMESPACE_URI,
    GPDOM_NODE_GET_PREFIX,
    GPDOM_NODE_SET_PREFIX,
    GPDOM_NODE_GET_LOCAL_NAME,
    GPDOM_NODE_HAS_ATTRIBUTES,
    GPDOM_NODE_GET_BASE_URI,
    GPDOM_NODE_COMPARE_DOCUMENT_POSITION,
    GPDOM_NODE_GET_TEXT_CONTENT,
    GPDOM_NODE_SET_TEXT_CONTENT,
    GPDOM_NODE_IS_SAME_NODE,
    GPDOM_NODE_LOOKUP_PREFIX,
    GPDOM_NODE_IS_DEFAULT_NAMESPACE,
    GPDOM_NODE_LOOKUP_NAMESPACE_URI,
    GPDOM_NODE_IS_EQUAL_NODE,
    GPDOM_NODE_GET_FEATURE,
    GPDOM_NODE_SET_USER_DATA,
    GPDOM_NODE_GET_USER_DATA,
    GPDOM_NODE_GET_LENGTH,
    GPDOM_NODE_LIST_ITEM,
    GPDOM_NAMED_NODE_MAP_GET_LENGTH,
    GPDOM_NAMED_NODE_MAP_GET_NAMED_ITEM,
    GPDOM_NAMED_NODE_MAP_SET_NAMED_ITEM,
    GPDOM_NAMED_NODE_MAP_REMOVE_NAMED_ITEM,
    GPDOM_NAMED_NODE_MAP_ITEM,
    GPDOM_NAMED_NODE_MAP_GET_ITEM_NS,
    GPDOM_NAMED_NODE_MAP_SET_ITEM_NS,
    GPDOM_NAMED_NODE_MAP_REMOVE_ITEM_NS,
    GPDOM_CHARACTER_DATA_GET_DATA,
    GPDOM_CHARACTER_DATA_SET_DATA,
    GPDOM_CHARACTER_DATA_GET_LENGTH,
    GPDOM_CHARACTER_DATA_SUBSTRING_DATA,
    GPDOM_CHARACTER_DATA_APPEND_DATA,
    GPDOM_CHARACTER_DATA_INSERT_DATA,
    GPDOM_CHARACTER_DATA_DELETE_DATA,
    GPDOM_CHARACTER_DATA_REPLACE_DATA,
    GPDOM_TEXT_SPLIT_TEXT,
    GPDOM_TEXT_GET_IS_ELEMENT_CONTENT_WHITESPACE,
    GPDOM_TEXT_GET_WHOLE_TEXT,
    GPDOM_TEXT_REPLACE_WHOLE_TEXT,
    GPDOM_ELEMENT_GET_TAG_NAME,
    GPDOM_ELEMENT_GET_ATTRIBUTE,
    GPDOM_ELEMENT_SET_ATTRIBUTE,
    GPDOM_ELEMENT_GET_TYPED_ATTRIBUTE,
    GPDOM_ELEMENT_SET_TYPED_ATTRIBUTE,
    GPDOM_ELEMENT_REMOVE_ATTRIBUTE,
    GPDOM_ELEMENT_GET_ATTRIBUTE_NODE,
    GPDOM_ELEMENT_SET_ATTRIBUTE_NODE,
    GPDOM_ELEMENT_GET_ELEMENTS_BY_TAG_NAME,
    GPDOM_ELEMENT_GET_ATTRIBUTE_NS,
    GPDOM_ELEMENT_GET_TYPED_ATTRIBUTE_NS,
    GPDOM_ELEMENT_SET_ATTRIBUTE_NS,
    GPDOM_ELEMENT_SET_TYPE_ATTRIBUTE_NS,
    GPDOM_ELEMENT_REMOVE_ATTRIBUTE_NS,
    GPDOM_ELEMENT_GET_ATTRIBUTE_NODE_NS,
    GPDOM_ELEMENT_SET_ATTRIBUTE_NODE_NS,
    GPDOM_ELEMENT_GET_ELEMENTS_BY_TAG_NAME_NS,
    GPDOM_ELEMENT_HAS_ATTRIBUTE,
    GPDOM_ELEMENT_HAS_ATTRIBUTE_NS,
    GPDOM_ELEMENT_GET_SCHEMA_TYPE_INFO,
    GPDOM_ELEMENT_SET_ID_ATTRIBUTE,
    GPDOM_ELEMENT_SET_ID_ATTRIBUTE_NS,
    GPDOM_ELEMENT_SET_ID_ATTRIBUTE_NODE,
    GPDOM_ATTR_GET_NAME,
    GPDOM_ATTR_GET_SPECIFIED,
    GPDOM_ATTR_GET_VALUE,
    GPDOM_ATTR_SET_VALUE,
    GPDOM_ATTR_GET_OWNER_ELEMENT,
    GPDOM_ATTR_GET_SCHEMA_TYPE_INFO,
    GPDOM_ATTR_IS_ID,
    GPDOM_DOCUMENT_GET_METHOD,
    GPDOM_DOCUMENT_GET_MEMBER,
    GPDOM_DOCUMENT_GET_DOCUMENT_VIEW,
    GPDOM_DOCUMENT_GET_DOCUMENT_TYPE,
    GPDOM_DOCUMENT_GET_DOM_IMPLEMENTATION,
    GPDOM_DOCUMENT_GET_DOCUMENT_ELEMENT,
    GPDOM_DOCUMENT_CREATE_ELEMENT,
    GPDOM_DOCUMENT_CREATE_DOCUMENT_FRAGMENT,
    GPDOM_DOCUMENT_CREATE_TEXT_NODE,
    GPDOM_DOCUMENT_CREATE_COMMENT,
    GPDOM_DOCUMENT_CREATE_CDATA_SECTION,
    GPDOM_DOCUMENT_CREATE_PROCESSING_INSTRUCTION,
    GPDOM_DOCUMENT_CREATE_ATTRIBUTE,
    GPDOM_DOCUMENT_CREATE_ENTITY_REFERENCE,
    GPDOM_DOCUMENT_GET_ELEMENTS_BY_TAG_NAME,
    GPDOM_DOCUMENT_IMPORT_NODE,
    GPDOM_DOCUMENT_CREATE_ELEMENT_NS,
    GPDOM_DOCUMENT_CREATE_ATTRIBUTE_NS,
    GPDOM_DOCUMENT_GET_ELEMENTS_BY_TAG_NAME_NS,
    GPDOM_DOCUMENT_GET_ELEMENTS_BY_ID,
    GPDOM_DOCUMENT_GET_INPUT_ENCODING,
    GPDOM_DOCUMENT_GET_XML_ENCODING,
    GPDOM_DOCUMENT_GET_XML_STANDALONE,
    GPDOM_DOCUMENT_SET_XML_STANDALONE,
    GPDOM_DOCUMENT_GET_XML_VERSION,
    GPDOM_DOCUMENT_SET_XML_VERSION,
    GPDOM_DOCUMENT_GET_STRICT_ERROR_CHECKING,
    GPDOM_DOCUMENT_SET_STRICT_ERROR_CHECKING,
    GPDOM_DOCUMENT_GET_DOCUMENT_URI,
    GPDOM_DOCUMENT_SET_DOCUMENT_URI,
    GPDOM_DOCUMENT_ADOPT_NODE,
    GPDOM_DOCUMENT_GET_DOM_CONFIGURATION,
    GPDOM_DOCUMENT_NORMALIZE_DOCUMENT,
    GPDOM_DOCUMENT_RENAME_NODE,
    GPDOM_DOM_CONFIGURATION_SET_PARAMETER,
    GPDOM_DOM_CONFIGURATION_GET_PARAMETER,
    GPDOM_DOM_CONFIGURATION_CAN_SET_PARAMETER,
    GPDOM_DOM_CONFIGURATION_GET_PARAMETER_NAMES,
    GPDOM_DOM_CONFIGURATION_GET_DOCUMENT_VIEW,
    GPDOM_DOM_EXTENSION,
} DOMFuncs;


#ifdef __cplusplus
}  /* end extern "C" */
#endif 

#endif /*GPDOMDefaultImpl_h*/
